### ISSUE TITLE
生成图片乱码

### ISSUE THREAD

**Issue by tediorelee** [Kokoro-js/koishi-plugin-word-cloud#3]
使用canvas：
![image](https://github.com/Kokoro-js/koishi-plugin-word-cloud/assets/48272067/42412569-5eee-4ce8-85ff-c5438d7b128c)

使用puppeteer: (只有寥寥几个词)
![image](https://github.com/Kokoro-js/koishi-plugin-word-cloud/assets/48272067/bc9f9d74-d7a7-4c8b-a7db-54d3d096c876)

**Comment by ahdg6** [comment]
canvas 缺乏字体导致的

**Comment by ahdg6** [comment]
你用的是 skia-canvas 的话把字体 https://github.com/lxgw/LxgwWenKai-Lite/releases/download/v1.320/lxgw-wenkai-lite-v1.320.tar.gz 丢到你设置的字体文件夹那，顺便解压了

**Comment by tediorelee** [comment]
> 你用的是 skia-canvas 的话把字体 https://github.com/lxgw/LxgwWenKai-Lite/releases/download/v1.320/lxgw-wenkai-lite-v1.320.tar.gz 丢到你设置的字体文件夹那，顺便解压了

已解决，确实是这个问题，多谢
